### ISSUE TITLE
exercises and solutions

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#55]
@tobyhodges 
May we ask your advice?

@manerotoni and I have discussed again the structure of the exercises and activities. We are thinking now that it would be nice to have the question part of the exercise language independent and then only have language specific solutions. 

Along those lines, do you think it could be ok to put the solutions directly into the module.md file rather than linking to language specific solution files? 

Main advantage, I think, it would be easier to contribute a new module (and also update solutions if the questions change) if one just needs to modify one file rather than multiple files distributed across different folders.

**Comment by tobyhodges** [comment]
Yes, this should be possible but would require some updates to the module layout. I am pretty busy with other stuff this week but could probably spare time to look at it Mon-Wed next week. Perhaps we should try to arrange a call to check in about this project before then, so I can get an idea of what else needs doing on my side?

The way I'm thinking about it right now, the exercises part of the YAML would end up looking something like this:

```yaml
exercise_text: "The question/text describing the exercise task goes here."
solutions:
  - language: "Jython"
    solution: >
code
goes
here
    highlighting: "language-python"
  - language: "ImageJ GUI"
    solution: >
solution
text here
    highlighting: false
```

The `language` property would be used to populate the dropdown menu of solutions, the `solution` property would contain the actual solution, and the `highlighting` property could be used to specify syntax highlighting for solutions in code, and Markdown rendering otherwise.
